language: c
#######################################################################################
os:
  - linux
  
addons:
  apt:
    packages:
      - curl

#######################################################################################


before_install:

  - sudo apt-get update -qq
  
  - git clone https://github.com/Manish4586/aarch64-linux-android-4.9 ~/aarch64-linux-android-4.9/
  
  - sudo chmod -R a+x *

#######################################################################################


script:  
  - export ARCH=arm64
  - export ARCH_QCOM_PLATFORM=sdm660
  - export CROSS_COMPILE=~/aarch64-linux-android-4.9/bin/aarch64-linux-android-
  - export KBUILD_BUILD_USER="root"
  - export KBUILD_BUILD_HOST="Manish4586"
  - mkdir out
  - make O=out jasmine-perf_defconfig
  - make O=out -j4

after_success:
  - curl --upload-file out/arch/arm64/boot/Image.gz-dtb https://filepush.co/upload/Image.gz-dtb
